### ISSUE TITLE
What is the purpose of this module?

### ISSUE THREAD

**Issue by eli-schwartz** [jreese/fissix#6]
fissix claims to be a backport of lib2to3. Maybe it would be better named as [backports](https://pypi.org/project/backports/).lib2to3?

I'm unclear what "with enhancements" is supposed to mean. As far as I can tell, `fissix.__init__` monkeypatches some things purely based around loading/saving the grammar, but the only other differences compared to stock lib2to3 are trivial formatting changes, because apparently running black on someone else's code is more important than being able to diff changes.

...

I'm considering packaging bowler for Arch Linux, but it seems like it requires me to create an additional fissix package too, and I don't understand why.

**Comment by jreese** [comment]
Tone aside, fissix is a backport specifically designed to be usable by standalone refactoring tools, namely Bowler. The monkeypatches allow fissix to cache grammar objects while being used from site-packages or other read-only directories, something that lib2to3 does not support. There are also some small patches for type annotation/checking purposes that were not readily accepted upstream. The formatting changes make the codebase dramatically easier (for me) to read and understand. 

All of these reasons are why it's not simply titled `backports.lib2to3`, because it is not a direct stand-in for lib2to3. Hardly different from the other half dozen forks of lib2to3 in use throughout the community.

**Comment by eli-schwartz** [comment]
The reason for my confusion is because I tried diffing it with the original CPython lib2to3 and I did not spot any differences whatsoever -- though I'll readily admit I may have been distracted by the diff contexts which modified single quotes to double quotes or added/removed whitespace.

Perhaps for the benefit of observers, you could discuss these practical changes in the README?

> The monkeypatches allow fissix to cache grammar objects while being used from site-packages or other read-only directories, something that lib2to3 does not support.

Maybe I'm missing something, but bowler at least does not seem to use this?

> There are also some small patches for type annotation/checking purposes that were not readily accepted upstream.

Could you point me to the patches in question? :) Thanks!

**Comment by jreese** [comment]
https://github.com/jreese/fissix/commit/2b6b47f717199e0fb602e464014246d9a459535c is the change that wasn't accepted upstream, but needed for purposes of type checking functions that could accept and operate on both leaves and nodes. I can't remember the BPO number offhand, but it can probably be found by searching BPO/cpython for PRs I created.

Most everything else was either upstreamed or contained to monkeypatches in `fissix/__init__.py`, and the history on master branch reflects all of these changes. Upstream changes are pulled into fissix via squashed merge commits, which leaves the master branch to primarily cover what makes fissix functionally separate.

I'll open an issue to clarify fissix's role in the readme.

**Comment by eli-schwartz** [comment]
Thanks, issue seems to be https://bugs.python.org/issue33983
